/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Conversation } from "./Conversation";
import { ConversationCountArgs } from "./ConversationCountArgs";
import { ConversationFindManyArgs } from "./ConversationFindManyArgs";
import { ConversationFindUniqueArgs } from "./ConversationFindUniqueArgs";
import { CreateConversationArgs } from "./CreateConversationArgs";
import { UpdateConversationArgs } from "./UpdateConversationArgs";
import { DeleteConversationArgs } from "./DeleteConversationArgs";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { ConversationService } from "../conversation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Conversation)
export class ConversationResolverBase {
  constructor(
    protected readonly service: ConversationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Conversation",
    action: "read",
    possession: "any",
  })
  async _conversationsMeta(
    @graphql.Args() args: ConversationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Conversation])
  @nestAccessControl.UseRoles({
    resource: "Conversation",
    action: "read",
    possession: "any",
  })
  async conversations(
    @graphql.Args() args: ConversationFindManyArgs
  ): Promise<Conversation[]> {
    return this.service.conversations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Conversation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Conversation",
    action: "read",
    possession: "own",
  })
  async conversation(
    @graphql.Args() args: ConversationFindUniqueArgs
  ): Promise<Conversation | null> {
    const result = await this.service.conversation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Conversation)
  @nestAccessControl.UseRoles({
    resource: "Conversation",
    action: "create",
    possession: "any",
  })
  async createConversation(
    @graphql.Args() args: CreateConversationArgs
  ): Promise<Conversation> {
    return await this.service.createConversation({
      ...args,
      data: {
        ...args.data,

        message: args.data.message
          ? {
              connect: args.data.message,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Conversation)
  @nestAccessControl.UseRoles({
    resource: "Conversation",
    action: "update",
    possession: "any",
  })
  async updateConversation(
    @graphql.Args() args: UpdateConversationArgs
  ): Promise<Conversation | null> {
    try {
      return await this.service.updateConversation({
        ...args,
        data: {
          ...args.data,

          message: args.data.message
            ? {
                connect: args.data.message,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Conversation)
  @nestAccessControl.UseRoles({
    resource: "Conversation",
    action: "delete",
    possession: "any",
  })
  async deleteConversation(
    @graphql.Args() args: DeleteConversationArgs
  ): Promise<Conversation | null> {
    try {
      return await this.service.deleteConversation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Message], { name: "messages" })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  async findMessages(
    @graphql.Parent() parent: Conversation,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Message, {
    nullable: true,
    name: "message",
  })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  async getMessage(
    @graphql.Parent() parent: Conversation
  ): Promise<Message | null> {
    const result = await this.service.getMessage(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
