/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PromptHistory } from "./PromptHistory";
import { PromptHistoryCountArgs } from "./PromptHistoryCountArgs";
import { PromptHistoryFindManyArgs } from "./PromptHistoryFindManyArgs";
import { PromptHistoryFindUniqueArgs } from "./PromptHistoryFindUniqueArgs";
import { CreatePromptHistoryArgs } from "./CreatePromptHistoryArgs";
import { UpdatePromptHistoryArgs } from "./UpdatePromptHistoryArgs";
import { DeletePromptHistoryArgs } from "./DeletePromptHistoryArgs";
import { Prompt } from "../../prompt/base/Prompt";
import { PromptHistoryService } from "../promptHistory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PromptHistory)
export class PromptHistoryResolverBase {
  constructor(
    protected readonly service: PromptHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PromptHistory",
    action: "read",
    possession: "any",
  })
  async _promptHistoriesMeta(
    @graphql.Args() args: PromptHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PromptHistory])
  @nestAccessControl.UseRoles({
    resource: "PromptHistory",
    action: "read",
    possession: "any",
  })
  async promptHistories(
    @graphql.Args() args: PromptHistoryFindManyArgs
  ): Promise<PromptHistory[]> {
    return this.service.promptHistories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PromptHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PromptHistory",
    action: "read",
    possession: "own",
  })
  async promptHistory(
    @graphql.Args() args: PromptHistoryFindUniqueArgs
  ): Promise<PromptHistory | null> {
    const result = await this.service.promptHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PromptHistory)
  @nestAccessControl.UseRoles({
    resource: "PromptHistory",
    action: "create",
    possession: "any",
  })
  async createPromptHistory(
    @graphql.Args() args: CreatePromptHistoryArgs
  ): Promise<PromptHistory> {
    return await this.service.createPromptHistory({
      ...args,
      data: {
        ...args.data,

        prompt: args.data.prompt
          ? {
              connect: args.data.prompt,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PromptHistory)
  @nestAccessControl.UseRoles({
    resource: "PromptHistory",
    action: "update",
    possession: "any",
  })
  async updatePromptHistory(
    @graphql.Args() args: UpdatePromptHistoryArgs
  ): Promise<PromptHistory | null> {
    try {
      return await this.service.updatePromptHistory({
        ...args,
        data: {
          ...args.data,

          prompt: args.data.prompt
            ? {
                connect: args.data.prompt,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PromptHistory)
  @nestAccessControl.UseRoles({
    resource: "PromptHistory",
    action: "delete",
    possession: "any",
  })
  async deletePromptHistory(
    @graphql.Args() args: DeletePromptHistoryArgs
  ): Promise<PromptHistory | null> {
    try {
      return await this.service.deletePromptHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Prompt, {
    nullable: true,
    name: "prompt",
  })
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "read",
    possession: "any",
  })
  async getPrompt(
    @graphql.Parent() parent: PromptHistory
  ): Promise<Prompt | null> {
    const result = await this.service.getPrompt(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
