/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PromptService } from "../prompt.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PromptCreateInput } from "./PromptCreateInput";
import { Prompt } from "./Prompt";
import { PromptFindManyArgs } from "./PromptFindManyArgs";
import { PromptWhereUniqueInput } from "./PromptWhereUniqueInput";
import { PromptUpdateInput } from "./PromptUpdateInput";
import { PromptHistoryFindManyArgs } from "../../promptHistory/base/PromptHistoryFindManyArgs";
import { PromptHistory } from "../../promptHistory/base/PromptHistory";
import { PromptHistoryWhereUniqueInput } from "../../promptHistory/base/PromptHistoryWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PromptControllerBase {
  constructor(
    protected readonly service: PromptService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Prompt })
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PromptCreateInput,
  })
  async createPrompt(@common.Body() data: PromptCreateInput): Promise<Prompt> {
    return await this.service.createPrompt({
      data: data,
      select: {
        category: true,
        content: true,
        createdAt: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Prompt] })
  @ApiNestedQuery(PromptFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prompts(@common.Req() request: Request): Promise<Prompt[]> {
    const args = plainToClass(PromptFindManyArgs, request.query);
    return this.service.prompts({
      ...args,
      select: {
        category: true,
        content: true,
        createdAt: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Prompt })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prompt(
    @common.Param() params: PromptWhereUniqueInput
  ): Promise<Prompt | null> {
    const result = await this.service.prompt({
      where: params,
      select: {
        category: true,
        content: true,
        createdAt: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Prompt })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PromptUpdateInput,
  })
  async updatePrompt(
    @common.Param() params: PromptWhereUniqueInput,
    @common.Body() data: PromptUpdateInput
  ): Promise<Prompt | null> {
    try {
      return await this.service.updatePrompt({
        where: params,
        data: data,
        select: {
          category: true,
          content: true,
          createdAt: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Prompt })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePrompt(
    @common.Param() params: PromptWhereUniqueInput
  ): Promise<Prompt | null> {
    try {
      return await this.service.deletePrompt({
        where: params,
        select: {
          category: true,
          content: true,
          createdAt: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/promptHistories")
  @ApiNestedQuery(PromptHistoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PromptHistory",
    action: "read",
    possession: "any",
  })
  async findPromptHistories(
    @common.Req() request: Request,
    @common.Param() params: PromptWhereUniqueInput
  ): Promise<PromptHistory[]> {
    const query = plainToClass(PromptHistoryFindManyArgs, request.query);
    const results = await this.service.findPromptHistories(params.id, {
      ...query,
      select: {
        change: true,
        createdAt: true,
        id: true,

        prompt: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/promptHistories")
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "update",
    possession: "any",
  })
  async connectPromptHistories(
    @common.Param() params: PromptWhereUniqueInput,
    @common.Body() body: PromptHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promptHistories: {
        connect: body,
      },
    };
    await this.service.updatePrompt({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/promptHistories")
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "update",
    possession: "any",
  })
  async updatePromptHistories(
    @common.Param() params: PromptWhereUniqueInput,
    @common.Body() body: PromptHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promptHistories: {
        set: body,
      },
    };
    await this.service.updatePrompt({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/promptHistories")
  @nestAccessControl.UseRoles({
    resource: "Prompt",
    action: "update",
    possession: "any",
  })
  async disconnectPromptHistories(
    @common.Param() params: PromptWhereUniqueInput,
    @common.Body() body: PromptHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promptHistories: {
        disconnect: body,
      },
    };
    await this.service.updatePrompt({
      where: params,
      data,
      select: { id: true },
    });
  }
}
